//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.17 at 02:51:16 PM CEST 
//

package org.universAAL.middleware.interfaces.mpa.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://universaal.org/aal-mpa/v1.0.0}deploymentUnit" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://universaal.org/aal-mpa/v1.0.0}executionUnit" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "deploymentUnit", "executionUnit" })
@XmlRootElement(name = "artifact")
public class Artifact {

    @XmlElement(required = true)
    protected List<DeploymentUnit> deploymentUnit;
    @XmlElement(required = true)
    protected List<ExecutionUnit> executionUnit;

    /**
     * Gets the value of the deploymentUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the deploymentUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDeploymentUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeploymentUnit }
     * 
     * 
     */
    public List<DeploymentUnit> getDeploymentUnit() {
	if (deploymentUnit == null) {
	    deploymentUnit = new ArrayList<DeploymentUnit>();
	}
	return this.deploymentUnit;
    }

    /**
     * Gets the value of the executionUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the executionUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getExecutionUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExecutionUnit }
     * 
     * 
     */
    public List<ExecutionUnit> getExecutionUnit() {
	if (executionUnit == null) {
	    executionUnit = new ArrayList<ExecutionUnit>();
	}
	return this.executionUnit;
    }

}
