//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.21 at 10:58:59 AM CEST 
//

package org.universAAL.middleware.interfaces.mpa.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="software" type="{http://universaal.org/aal-mpa/v1.0.0}ArtifactType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "software" })
@XmlRootElement(name = "brokers")
public class Brokers {

    @XmlElement(required = true)
    protected ArtifactType software;

    /**
     * Gets the value of the software property.
     * 
     * @return possible object is {@link ArtifactType }
     * 
     */
    public ArtifactType getSoftware() {
	return software;
    }

    /**
     * Sets the value of the software property.
     * 
     * @param value
     *            allowed object is {@link ArtifactType }
     * 
     */
    public void setSoftware(ArtifactType value) {
	this.software = value;
    }

}
