//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.28 at 11:17:02 AM CEST 
//

package org.universAAL.middleware.interfaces.mpa.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ProfileType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="profileId" type="{http://universaal.org/aal-mpa/v1.0.0}SpaceType"/>
 *         &lt;element name="version" type="{http://universaal.org/aal-mpa/v1.0.0}VersionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProfileType", propOrder = { "profileId", "version" })
public class ProfileType implements Serializable {

    private final static long serialVersionUID = 12343L;
    @XmlElement(required = true)
    protected SpaceType profileId;
    @XmlElement(required = true)
    protected VersionType version;

    /**
     * Gets the value of the profileId property.
     * 
     * @return possible object is {@link SpaceType }
     * 
     */
    public SpaceType getProfileId() {
	return profileId;
    }

    /**
     * Sets the value of the profileId property.
     * 
     * @param value
     *            allowed object is {@link SpaceType }
     * 
     */
    public void setProfileId(SpaceType value) {
	this.profileId = value;
    }

    public boolean isSetProfileId() {
	return (this.profileId != null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link VersionType }
     * 
     */
    public VersionType getVersion() {
	return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *            allowed object is {@link VersionType }
     * 
     */
    public void setVersion(VersionType value) {
	this.version = value;
    }

    public boolean isSetVersion() {
	return (this.version != null);
    }

}
