//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.28 at 11:17:02 AM CEST 
//

package org.universAAL.middleware.interfaces.mpa.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for VersionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="VersionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="major" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="minor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="micro" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="build" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionType", propOrder = { "major", "minor", "micro",
	"build", "string" })
public class VersionType implements Serializable {

    private final static long serialVersionUID = 12343L;
    @XmlElement(defaultValue = "0")
    protected int major;
    @XmlElement(defaultValue = "0")
    protected int minor;
    @XmlElement(defaultValue = "0")
    protected int micro;
    protected String build;
    @XmlElement(required = true)
    protected String string;

    /**
     * Gets the value of the major property.
     * 
     */
    public int getMajor() {
	return major;
    }

    /**
     * Sets the value of the major property.
     * 
     */
    public void setMajor(int value) {
	this.major = value;
    }

    public boolean isSetMajor() {
	return true;
    }

    /**
     * Gets the value of the minor property.
     * 
     */
    public int getMinor() {
	return minor;
    }

    /**
     * Sets the value of the minor property.
     * 
     */
    public void setMinor(int value) {
	this.minor = value;
    }

    public boolean isSetMinor() {
	return true;
    }

    /**
     * Gets the value of the micro property.
     * 
     */
    public int getMicro() {
	return micro;
    }

    /**
     * Sets the value of the micro property.
     * 
     */
    public void setMicro(int value) {
	this.micro = value;
    }

    public boolean isSetMicro() {
	return true;
    }

    /**
     * Gets the value of the build property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBuild() {
	return build;
    }

    /**
     * Sets the value of the build property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBuild(String value) {
	this.build = value;
    }

    public boolean isSetBuild() {
	return (this.build != null);
    }

    /**
     * Gets the value of the string property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getString() {
	return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setString(String value) {
	this.string = value;
    }

    public boolean isSetString() {
	return (this.string != null);
    }

}
