//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.10 at 02:38:44 PM CEST 
//

package org.universAAL.middleware.connectors.deploy.karaf.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * 
 * Deployable element to install.
 * 
 * 
 * <p>
 * Java class for bundle complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="bundle">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *       &lt;attribute name="start-level" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dependency" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bundle", propOrder = { "value" })
public class Bundle {

    @XmlValue
    @XmlSchemaType(name = "anyURI")
    protected String value;
    @XmlAttribute(name = "start-level")
    protected Integer startLevel;
    @XmlAttribute(name = "start")
    protected Boolean start;
    @XmlAttribute(name = "dependency")
    protected Boolean dependency;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
	return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
	this.value = value;
    }

    /**
     * Gets the value of the startLevel property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getStartLevel() {
	return startLevel;
    }

    /**
     * Sets the value of the startLevel property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setStartLevel(Integer value) {
	this.startLevel = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isStart() {
	return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setStart(Boolean value) {
	this.start = value;
    }

    /**
     * Gets the value of the dependency property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isDependency() {
	return dependency;
    }

    /**
     * Sets the value of the dependency property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setDependency(Boolean value) {
	this.dependency = value;
    }

}
