package org.universAAL.middleware.managers.api;

import org.universAAL.middleware.interfaces.PeerCard;
import org.universAAL.middleware.interfaces.mpa.UAPPCard;
import org.universAAL.middleware.interfaces.mpa.UAPPPartStatus;

/**
 * Callback interface for the Events generated by the DeployManager
 * 
 * @author <a href="mailto:michele.girolami@isti.cnr.it">Michele Girolami</a>
 * @author <a href="mailto:francesco.furfari@isti.cnr.it">Francesco Furfari</a>
 * @author <a href="mailto:stefano.lenzi@isti.cnr.it">Stefano Lenzi</a>
 * @version $LastChangedRevision$ ( $LastChangedDate$ )
 * 
 */
public interface DeployManagerEventHandler {

    /**
     * Method called back in order to notifiy the result of a request to install
     * 
     * @param peer
     *            The Peer sending the result
     * @param uappCard
     *            The MPA to whic the peer refers to
     * @param partID
     *            Part id
     * @param partStatus
     *            Status of the part
     */
    public void installationPartNotification(UAPPCard uappCard, String partID,
	    PeerCard peer, UAPPPartStatus partStatus);

}
