//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.17 at 04:00:26 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.universaal.org/aal-uapp/v1.0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.universAAL.middleware.deploymanager.uapp.model;
