//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 06:22:00 PM CET 
//


package org.universAAL.middleware.interfaces.aalspace.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This schema describes the meta-information of an
 *         AALSpace Channel
 *       
 * 
 * <p>Java class for channelDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="channelDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="channelURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="channelValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "channelDescriptor", propOrder = {
    "channelName",
    "channelURL",
    "channelValue"
})
public class ChannelDescriptor
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(namespace = "http://universaal.org/aalspace-channel/v1.0.0", required = true)
    protected String channelName;
    @XmlElement(namespace = "http://universaal.org/aalspace-channel/v1.0.0", required = true)
    protected String channelURL;
    @XmlElement(namespace = "http://universaal.org/aalspace-channel/v1.0.0", required = true)
    protected String channelValue;

    /**
     * Gets the value of the channelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * Sets the value of the channelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelName(String value) {
        this.channelName = value;
    }

    public boolean isSetChannelName() {
        return (this.channelName!= null);
    }

    /**
     * Gets the value of the channelURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelURL() {
        return channelURL;
    }

    /**
     * Sets the value of the channelURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelURL(String value) {
        this.channelURL = value;
    }

    public boolean isSetChannelURL() {
        return (this.channelURL!= null);
    }

    /**
     * Gets the value of the channelValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelValue() {
        return channelValue;
    }

    /**
     * Sets the value of the channelValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelValue(String value) {
        this.channelValue = value;
    }

    public boolean isSetChannelValue() {
        return (this.channelValue!= null);
    }

}
