//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 06:22:00 PM CET 
//


package org.universAAL.middleware.interfaces.aalspace.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.universAAL.middleware.interfaces.aalspace.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.universAAL.middleware.interfaces.aalspace.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aalspace }
     * 
     */
    public Aalspace createAalspace() {
        return new Aalspace();
    }

    /**
     * Create an instance of {@link ChannelDescriptor }
     * 
     */
    public ChannelDescriptor createChannelDescriptor() {
        return new ChannelDescriptor();
    }

    /**
     * Create an instance of {@link Aalspace.SpaceDescriptor }
     * 
     */
    public Aalspace.SpaceDescriptor createAalspaceSpaceDescriptor() {
        return new Aalspace.SpaceDescriptor();
    }

    /**
     * Create an instance of {@link Aalspace.PeeringChannel }
     * 
     */
    public Aalspace.PeeringChannel createAalspacePeeringChannel() {
        return new Aalspace.PeeringChannel();
    }

    /**
     * Create an instance of {@link Aalspace.CommunicationChannels }
     * 
     */
    public Aalspace.CommunicationChannels createAalspaceCommunicationChannels() {
        return new Aalspace.CommunicationChannels();
    }

}
