//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 06:22:00 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://universaal.org/aalspace-channel/v1.0.0")
package org.universAAL.middleware.interfaces.aalspace.model;
