package org.universAAL.middleware.bus.model.test;


import org.universAAL.middleware.bus.model.Permission;

import junit.framework.TestCase;

public class PermissionTest extends TestCase {

    public void testFromManifest1() {
	String entry = "Get controlled lamps---<\r\n"
		+ " /title>---get the identifiers of all lamps that are controlled by thi\r\n"
		+ " s component.---</description>---@prefix ns: <http://www.daml.org/serv\r\n"
		+ " ices/owl-s/1.1/Service.owl#> . @prefix ns1: <http://www.daml.org/serv\r\n"
		+ " ices/owl-s/1.1/Process.owl#> . @prefix ns2: <http://www.daml.org/serv\r\n"
		+ " ices/owl-s/1.1/Profile.owl#> . @prefix : <http://ontology.igd.fhg.de/\r\n"
		+ " LightingServer.owl#> . _:BN000000 ns:presentedBy :getControlledLamps \r\n"
		+ " ; a ns2:Profile ; ns2:has_process :getControlledLampsProcess ; ns2:ha\r\n"
		+ " sResult [ ns1:withOutput [ a ns1:OutputBinding ; ns1:toParam :control\r\n"
		+ " ledLamps ; ns1:valueForm \"\"\" @prefix : <http://ontology.universAAL.or\r\n"
		+ " g/Service.owl#> . _:BN000000 a :PropertyPath ; :thePath ( <http://ont\r\n"
		+ " ology.universaal.org/Lighting.owl#controls> ) . \"\"\"^^<http://www.w3.o\r\n"
		+ " rg/1999/02/22-rdf-syntax-ns#XMLLiteral> ] ; a ns1:Result ] ; ns2:hasO\r\n"
		+ " utput :controlledLamps . :controlledLamps a ns1:Output ; ns1:paramete\r\n"
		+ " rType \"http://ontology.universaal.org/Lighting.owl#LightSource\"^^<htt\r\n"
		+ " p://www.w3.org/2001/XMLSchema#anyURI> . :getControlledLamps a :Lighti\r\n"
		+ " ngService , <http://ontology.universaal.org/Lighting.owl#Lighting> ; \r\n"
		+ " ns:presents _:BN000000 .---</serialization>---Get lamp info---</title\r\n"
		+ " >---Get information about a specific light source, i.e. its location \r\n"
		+ " and brightness.---</description>---@prefix ns: <http://www.daml.org/s\r\n"
		+ " ervices/owl-s/1.1/Profile.owl#> . @prefix pvn: <http://ontology.unive\r\n"
		+ " rsAAL.org/uAAL.owl#> . @prefix owl: <http://www.w3.org/2002/07/owl#> \r\n"
		+ " . @prefix ns1: <http://ontology.igd.fhg.de/LightingServer.owl#> . @pr\r\n"
		+ " efix ns2: <http://www.daml.org/services/owl-s/1.1/Service.owl#> . @pr\r\n"
		+ " efix ns3: <http://ontology.universaal.org/Lighting.owl#> . @prefix xs\r\n"
		+ " d: <http://www.w3.org/2001/XMLSchema#> . @prefix psn: <http://ontolog\r\n"
		+ " y.universAAL.org/Service.owl#> . @prefix rdf: <http://www.w3.org/1999\r\n"
		+ " /02/22-rdf-syntax-ns#> . @prefix : <http://www.daml.org/services/owl-\r\n"
		+ " s/1.1/Process.owl#> . _:BN000000 ns2:presentedBy ns1:getLampInfo ; a \r\n"
		+ " ns:Profile ; ns:has_process ns1:getLampInfoProcess ; ns:hasResult [ :\r\n"
		+ " withOutput [ a :OutputBinding ; :toParam ns1:brightness ; :valueForm \r\n"
		+ " \"\"\" @prefix ns: <http://ontology.universaal.org/Lighting.owl#> . @pre\r\n"
		+ " fix : <http://ontology.universAAL.org/Service.owl#> . _:BN000000 a :P\r\n"
		+ " ropertyPath ; :thePath ( ns:controls ns:srcBrightness ) . \"\"\"^^rdf:XM\r\n"
		+ " LLiteral ] , [ a :OutputBinding ; :toParam ns1:location ; :valueForm \r\n"
		+ " \"\"\" @prefix : <http://ontology.universAAL.org/Service.owl#> . _:BN000\r\n"
		+ " 000 a :PropertyPath ; :thePath ( <http://ontology.universaal.org/Ligh\r\n"
		+ " ting.owl#controls> <http://ontology.universaal.org/PhThing.owl#hasLoc\r\n"
		+ " ation> ) . \"\"\"^^rdf:XMLLiteral ] ; a :Result ] ; ns:hasOutput ns1:bri\r\n"
		+ " ghtness , ns1:location ; ns:hasInput ns1:lampURI . :ThisPerform a :Pe\r\n"
		+ " rform . ns1:getLampInfo a ns1:LightingService , ns3:Lighting ; pvn:in\r\n"
		+ " stanceLevelRestrictions [ owl:hasValue [ :fromProcess :ThisPerform ; \r\n"
		+ " a :ValueOf ; :theVar ns1:lampURI ] ; a owl:Restriction ; owl:onProper\r\n"
		+ " ty ns3:controls ] ; ns2:presents _:BN000000 ; pvn:numberOfValueRestri\r\n"
		+ " ctions \"1\"^^xsd:int . ns1:brightness psn:parameterCardinality \"1\"^^xs\r\n"
		+ " d:int ; a :Output ; :parameterType \"http://www.w3.org/2001/XMLSchema#\r\n"
		+ " int\"^^xsd:anyURI . ns1:lampURI psn:parameterCardinality \"1\"^^xsd:int \r\n"
		+ " ; a :Input ; :parameterType \"http://ontology.universaal.org/Lighting.\r\n"
		+ " owl#LightSource\"^^xsd:anyURI . ns1:location psn:parameterCardinality \r\n"
		+ " \"1\"^^xsd:int ; a :Output ; :parameterType \"http://ontology.universAAL\r\n"
		+ " .org/Location.owl#Location\"^^xsd:anyURI .---</serialization>---Turn l\r\n"
		+ " ight off---</title>---Turn off a specific light source.---</descripti\r\n"
		+ " on>---@prefix ns: <http://www.daml.org/services/owl-s/1.1/Profile.owl\r\n"
		+ " #> . @prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> . @prefi\r\n"
		+ " x owl: <http://www.w3.org/2002/07/owl#> . @prefix ns1: <http://ontolo\r\n"
		+ " gy.igd.fhg.de/LightingServer.owl#> . @prefix ns2: <http://www.daml.or\r\n"
		+ " g/services/owl-s/1.1/Service.owl#> . @prefix ns3: <http://ontology.un\r\n"
		+ " iversaal.org/Lighting.owl#> . @prefix xsd: <http://www.w3.org/2001/XM\r\n"
		+ " LSchema#> . @prefix psn: <http://ontology.universAAL.org/Service.owl#\r\n"
		+ " > . @prefix : <http://www.daml.org/services/owl-s/1.1/Process.owl#> .\r\n"
		+ "  _:BN000000 ns2:presentedBy ns1:turnOff ; a ns:Profile ; ns:has_proce\r\n"
		+ " ss ns1:turnOffProcess ; ns:hasResult [ a :Result ; :hasEffect [ psn:a\r\n"
		+ " ffectedProperty [ a psn:PropertyPath ; psn:thePath ( ns3:controls ns3\r\n"
		+ " :srcBrightness ) ] ; a psn:ChangeEffect ; psn:propertyValue \"0\"^^xsd:\r\n"
		+ " int ] ] ; ns:hasInput ns1:lampURI . ns1:turnOff a ns1:LightingService\r\n"
		+ "  , ns3:Lighting ; pvn:instanceLevelRestrictions [ owl:hasValue [ :fro\r\n"
		+ " mProcess :ThisPerform ; a :ValueOf ; :theVar ns1:lampURI ] ; a owl:Re\r\n"
		+ " striction ; owl:onProperty ns3:controls ] ; ns2:presents _:BN000000 ;\r\n"
		+ "  pvn:numberOfValueRestrictions \"1\"^^xsd:int . ns1:lampURI psn:paramet\r\n"
		+ " erCardinality \"1\"^^xsd:int ; a :Input ; :parameterType \"http://ontolo\r\n"
		+ " gy.universaal.org/Lighting.owl#LightSource\"^^xsd:anyURI . :ThisPerfor\r\n"
		+ " m a :Perform .---</serialization>---Turn light on---</title>---Turn o\r\n"
		+ " n a specific light source.---</description>---@prefix ns: <http://www\r\n"
		+ " .daml.org/services/owl-s/1.1/Profile.owl#> . @prefix pvn: <http://ont\r\n"
		+ " ology.universAAL.org/uAAL.owl#> . @prefix owl: <http://www.w3.org/200\r\n"
		+ " 2/07/owl#> . @prefix ns1: <http://ontology.igd.fhg.de/LightingServer.\r\n"
		+ " owl#> . @prefix ns2: <http://www.daml.org/services/owl-s/1.1/Service.\r\n"
		+ " owl#> . @prefix ns3: <http://ontology.universaal.org/Lighting.owl#> .\r\n"
		+ "  @prefix xsd: <http://www.w3.org/2001/XMLSchema#> . @prefix psn: <htt\r\n"
		+ " p://ontology.universAAL.org/Service.owl#> . @prefix : <http://www.dam\r\n"
		+ " l.org/services/owl-s/1.1/Process.owl#> . _:BN000000 ns2:presentedBy n\r\n"
		+ " s1:turnOn ; a ns:Profile ; ns:has_process ns1:turnOnProcess ; ns:hasR\r\n"
		+ " esult [ a :Result ; :hasEffect [ psn:affectedProperty [ a psn:Propert\r\n"
		+ " yPath ; psn:thePath ( ns3:controls ns3:srcBrightness ) ] ; a psn:Chan\r\n"
		+ " geEffect ; psn:propertyValue \"100\"^^xsd:int ] ] ; ns:hasInput ns1:lam\r\n"
		+ " pURI . ns1:turnOn a ns1:LightingService , ns3:Lighting ; pvn:instance\r\n"
		+ " LevelRestrictions [ owl:hasValue [ :fromProcess :ThisPerform ; a :Val\r\n"
		+ " ueOf ; :theVar ns1:lampURI ] ; a owl:Restriction ; owl:onProperty ns3\r\n"
		+ " :controls ] ; ns2:presents _:BN000000 ; pvn:numberOfValueRestrictions\r\n"
		+ "  \"1\"^^xsd:int . ns1:lampURI psn:parameterCardinality \"1\"^^xsd:int ; a\r\n"
		+ "  :Input ; :parameterType \"http://ontology.universaal.org/Lighting.owl\r\n"
		+ " #LightSource\"^^xsd:anyURI . :ThisPerform a :Perform .---</serializati\r\n"
		+ " on>---";
	entry = entry.replace("\r\n ", "");

	Permission[] perms = Permission.parsePermission(entry);
	assertTrue(perms.length == 4);
    }
}
